package com.mcf.davidee.guilib;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import java.util.Arrays;


@Mod(modid = "guilib", name = "GUILibrary", version = "1.0")
public class GuiLibrary {

	
	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Davidee", "ph1823" });
		modMeta.autogenerated = false;
		modMeta.credits = "Thanks to Mojang, Forge, and all your support.Davidee Coded mods 1.8 and update by ph1823.";
		modMeta.description = "A small library for creating minecraft GUIs.";
		modMeta.url = "http://www.minecraftforum.net/topic/1909236-/";
	}
	
}
